### ISSUE TITLE
Permission Error

### ISSUE THREAD

**Issue by rightisleft** [HannesRammer/Dartabase#24]
Trying to follow along with the Dartabase tutorials. 

When i get to the dbinit steps i get the following error:

➜  bin git:(todolist) dart dbInit.dart 
|--------------------------|
|   Dartabase initiation   |
|--------------------------|

!!ONLY RUN THIS ONCE FOR EACH PROJECT!!

Please type or paste a project name and press the ENTER key
todo
Please enter the absolute path to your project root folder and press the ENTER key to proceed
eg. c:\DartProjects\myApp
take care of capital letters!!
/Users/jmurphy/projects/DartabaseTutorials/examples/PreTutorialMixApp
add project mapping todo:/Users/jmurphy/projects/DartabaseTutorials/examples/PreTutorialMixApp
created directory /Users/jmurphy/projects/DartabaseTutorials/examples/PreTutorialMixApp/db/migrations
creating /Users/jmurphy/projects/DartabaseTutorials/examples/PreTutorialMixApp/db/config.json
creating /Users/jmurphy/projects/DartabaseTutorials/examples/PreTutorialMixApp/db/schema.json
creating /Users/jmurphy/projects/DartabaseTutorials/examples/PreTutorialMixApp/db/schemaVersion.json

add project mapping todo:
Unhandled exception:
Uncaught Error: FileSystemException: Creation failed, path = '/db' (OS Error: Permission denied, errno = 13)
Stack Trace:
#0      _Directory.create.<anonymous closure> (dart:io/directory_impl.dart:108)
#1      _RootZone.runUnary (dart:async/zone.dart:1155)
#2      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:484)
#3      _Future._propagateToListeners (dart:async/future_impl.dart:567)
#4      _Future._completeWithValue (dart:async/future_impl.dart:358)
#5      _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:412)
#6      _asyncRunCallbackLoop (dart:async/schedule_microtask.dart:41)
#7      _asyncRunCallback (dart:async/schedule_microtask.dart:48)
#8      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:84)
#9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:131)

#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:886)
#1      _asyncRunCallbackLoop (dart:async/schedule_microtask.dart:41)
#2      _asyncRunCallback (dart:async/schedule_microtask.dart:48)
#3      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:84)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:131)

When i look at the target folder i see the following:

➜  db git:(tutorial) ✗ pwd
/Users/jmurphy/projects/DartabaseTutorials/examples/PreTutorialMixApp/db
➜  db git:(tutorial) ✗ tree
.
├── config.json
├── migrations
├── schema.json
└── schemaVersion.json

1 directory, 3 files

**Comment by rightisleft** [comment]
Seems to the key to the map isn't returning a valid rootPath.

projectMappings.json look odd:
{"Todo":"","todo":"","/Users/jmurphy/projects/DartabaseTutorials/examples/PreTutorialMixApp":""}

Looks like the 'line' variable will result in a value of: "" (empty string)

This would causes the directory to be assigned to system root, causing the above error.

**Comment by rightisleft** [comment]
Fix Here: https://github.com/HannesRammer/Dartabase/pull/25
